export default {
	FETCH_POSTS: 'FETCH_POSTS',
	FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',

	SAVE_POST: 'SAVE_POST',
	SAVE_POST_SUCCESS: 'SAVE_POST_SUCCESS',

	FETCH_POST: 'FETCH_POST',
	FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',

	DELETE_POST: 'DELETE_POST',
	DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS'
};